name: Build Images

on:
  workflow_dispatch:
    inputs:
      registry:
        description: 'Image registry'
        required: true
        default: 'jibutech-registry.cn-hangzhou.cr.aliyuncs.com'
        type: choice
        options:
        - jibutech-registry.cn-hangzhou.cr.aliyuncs.com
        - docker.io
      platform:
        description: 'Build images on different platform'
        required: true
        default: 'linux/amd64'
        type: choice
        options:
        - linux/amd64
        - linux/arm64
        - linux/amd64,linux/arm64

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Jibutech Alicloud Docker registry
      if: inputs.registry == 'jibutech-registry.cn-hangzhou.cr.aliyuncs.com'
      uses: docker/login-action@v2
      with:
        registry: jibutech-registry.cn-hangzhou.cr.aliyuncs.com
        repo: ys1000
        username: ${{ secrets.JIBUTECH_ALI_REGISTRY_USER }}
        password: ${{ secrets.JIBUTECH_ALI_REGISTRY_PASS }}
    - name: Login to Docker registry
      if: inputs.registry == 'docker.io'
      uses: docker/login-action@v2
      with:
        registry: docker.io
        repo: jibutech
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_PASS }}
    - name: Build and push Docker images
      run: |
        GOPROXY=https://proxy.golang.org,direct PLATFORM=${PLATFORM} IMAGE_PREFIX=${REGISTRY}/ys1000 make -f Makefile.new container
      env:
        PLATFORM: ${{ inputs.platform }}
        REGISTRY: ${{ inputs.registry }}
